title: Vademecum
author: Jan Arends, Ate Snijder, Basia van Vliet, Stijn Brancart, Pim Buskermolen, Julia Schönwälder, Dirk Rinze Visser, Silke Prinsse, Ertuğ Çiftçi, Silke Prinsse, Minke van den Boogaard, Niels van Vliet, Guus Meinema © Copyright Delft University of Technology, CC BY 4.0.
logo: figures/voorblad.png #add your own logo here

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/favicon.ico"
  baseurl :  "https://teachbooks.github.io/Vademecum/" #Replace this with your own URL

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://github.com/TeachBooks/Vademecum" #add your own repo URL here
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
  extra_extensions:
    - sphinx.ext.imgconverter
    # - jupyterbook_patches
    # - download_link_replacer
    - sphinx.ext.extlinks
  mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist



bibtex_bibfiles: 
  - references.bib
